### ISSUE TITLE
Malformed preview for files of MIME type `application/x-empty`

### ISSUE THREAD

**Issue by fdnt7** [Reledia/hexyl.yazi#2]
### Summary
Using this plugin previewer to preview files of MIME type `application/x-empty` shows a truncated preview.

### Steps to Reproduce
1. have `hexyl` in your `PATH`
2. follow the instructions in the project [`README`](https://github.com/Reledia/hexyl.yazi/blob/main/README.md)
3. run `yazi`
4. select a file of MIME type `application/x-empty` and notice the preview.

### Expected Behaviour
The previewer shows a text-only saying "No Content", possibly centre-aligned to the preview area, to be in line with Yazi's default preview of an empty directory (which shows "No items").

### Actual Behaviour
The previewer shows:
![image](https://github.com/Reledia/hexyl.yazi/assets/43757589/71479839-4d3c-47e0-a6d4-e279fd2f6c44)

with multiple `|` characters, which makes the preview look malformed.

### Additional Information
The preview is a top-bottom-truncated version of doing `hexyl <file of MIME type application/x-empty>`:
![image](https://github.com/Reledia/hexyl.yazi/assets/43757589/6e09889e-f2cf-4312-98b6-31fa4ba5cdf2)

which looks well-formed (as a table). However, the resulting truncated version that was used to be a preview appears as if it was a mistake, rather than an intentional preview.

**Comment by Reledia** [comment]
Fixed in 64daf93. If it works for you too close the issue,thanks

**Comment by fdnt7** [comment]
> Fixed in [64daf93](https://github.com/Reledia/hexyl.yazi/commit/64daf93a67d75eff871befe52d9013687171ffad). If it works for you too close the issue,thanks

This works, thank you for the quick fix. 

FYI, It may be truncated from the right, like so:
![image](https://github.com/Reledia/hexyl.yazi/assets/43757589/19c57f7b-8657-437f-a11a-51675d3569f2)
unlike previewing some other binaries, which allocates a lot of space on the right:
![image](https://github.com/Reledia/hexyl.yazi/assets/43757589/39013a48-61e7-4f7e-a8d4-205b6613b04e)

I'll close the issue now since the preview looks well-formed now.
