### ISSUE TITLE
RuntimeError, a nil value

### ISSUE THREAD

**Issue by SH-ke** [Reledia/hexyl.yazi#4]
# error log : 

  2024-10-24T08:15:56.411010Z ERROR yazi_plugin::isolate::peek: RuntimeError("[string \"hexyl\"]:49: attempt to index a nil value (field 'Text')\nstack traceback:\n\t[string \"hexyl\"]:49: in function <[string \"hexyl\"]:3>")
    at yazi-plugin/src/isolate/peek.rs:50

  2024-10-24T08:15:56.594781Z ERROR yazi_plugin::isolate::peek: RuntimeError("[string \"hexyl\"]:49: attempt to index a nil value (field 'Text')\nstack traceback:\n\t[string \"hexyl\"]:49: in function <[string \"hexyl\"]:3>")
    at yazi-plugin/src/isolate/peek.rs:50

# yazi.toml:
...
	\# Empty file
	{ mime = "inode/x-empty", run = "empty" },
	\# Fallback
	{ name = "*", run = "file" },
]

prepend_previewers = [
  \# ya plugins
  \# ya plugins
  { name = "*", run = "hexyl" }, # bin files
  { name = "*/", run = "eza-preview" }, # show file tree
  { mime = "application/x-bittorrent", run = "torrent-preview"},
  { mime = "{image,audio,video}/*", run = "mediainfo"},
  { mime = "application/x-subrip", run = "mediainfo"},

  { name = "*.csv", run = "rich-preview"}, # for csv files
  { name = "*.md", run = "rich-preview" }, # for markdown (.md) files
  { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
  { name = "*.json", run = "rich-preview"}, # for json (.json) files
  { name = "*.lang_type", run = "rich-preview"}, # for particular language files eg. .py, .go., .lua, etc.
]

...

# keymap.toml:
...
	\# Help
	{ on = "~",    run = "help", desc = "Open help" },
	{ on = "<F1>", run = "help", desc = "Open help" },
]
\# [[manager.prepend_keymap]]
prepend_keymap = [
  { on  = "K", run = "plugin --sync parent-arrow --args=-1" },
  { on  = "J", run = "plugin --sync parent-arrow --args=1" },
  { on  = "E", run = "plugin eza-preview",  desc = "Toggle tree/list dir preview" },
]

...

# question
Q: how to solve this error ? and my yzai could not show the bin preview of hexyl, em it does not work maybe.
I have installed hexyl, hexyl.yazi, and have set the yazi.toml above, do nothing in keymap.yazi. Are there any other details that need attention?

**Comment by Reledia** [comment]
Is this the same issue as https://github.com/Reledia/glow.yazi/issues/11? If yes, try to update to the latest version of yazi

**Comment by Reledia** [comment]
Is this the same issue as https://github.com/Reledia/glow.yazi/issues/11? If yes, try to update to the latest version of yazi

**Comment by SH-ke** [comment]
yes, you are right, get the latest version works, thank you.
i used the stable version Yazi 0.3.3-1 ( 2024-9)
and now update to the latest, Yazi 0.3.3 (fd8871d8 2024-11-10)
